### ISSUE TITLE
Add a search modal

### ISSUE THREAD

**Issue by vascoguita** [gethugothemes/bigspring-light-hugo#73]

**Comment by tfsomrat** [comment]
Hi @vascoguita, thanks for your interest. you don't have any plan to add a search modal right now. thanks

**Comment by vascoguita** [comment]
Hi @tfsomrat, thank you for replying.
Would you accept my Pull Request if I disable it the search modal by default? https://github.com/gethugothemes/bigspring-light-hugo/pull/74

When enabled, it looks like this:
![image](https://github.com/gethugothemes/bigspring-light-hugo/assets/33404234/7a5f6a20-4719-4472-b08d-03d1499502ae)
